var _analysis =
[
    [ "Reweighting and Averaging", "_analysis.html#analysisbias", null ],
    [ "Diagnostic tools", "_analysis.html#diag", null ],
    [ "Storing data for analysis", "_analysis.html#storing", null ],
    [ "Calculating dissimilarity matrices", "_analysis.html#dissimilaritym", null ],
    [ "Landmark Selection", "_analysis.html#landmarks", null ],
    [ "Dimensionality Reduction", "_analysis.html#dimred", null ],
    [ "Outputting the results from analysis algorithms", "_analysis.html#output", null ],
    [ "COMMITTOR", "_c_o_m_m_i_t_t_o_r.html", null ],
    [ "DUMPATOMS", "_d_u_m_p_a_t_o_m_s.html", null ],
    [ "DUMPDERIVATIVES", "_d_u_m_p_d_e_r_i_v_a_t_i_v_e_s.html", null ],
    [ "DUMPFORCES", "_d_u_m_p_f_o_r_c_e_s.html", null ],
    [ "DUMPMASSCHARGE", "_d_u_m_p_m_a_s_s_c_h_a_r_g_e.html", null ],
    [ "DUMPMULTICOLVAR", "_d_u_m_p_m_u_l_t_i_c_o_l_v_a_r.html", null ],
    [ "DUMPPROJECTIONS", "_d_u_m_p_p_r_o_j_e_c_t_i_o_n_s.html", null ],
    [ "PRINT", "_p_r_i_n_t.html", "_p_r_i_n_t" ],
    [ "UPDATE_IF", "_u_p_d_a_t_e__i_f.html", null ],
    [ "REWEIGHT_BIAS", "_r_e_w_e_i_g_h_t__b_i_a_s.html", null ],
    [ "REWEIGHT_METAD", "_r_e_w_e_i_g_h_t__m_e_t_a_d.html", null ],
    [ "REWEIGHT_TEMP_PRESS", "_r_e_w_e_i_g_h_t__t_e_m_p__p_r_e_s_s.html", null ],
    [ "REWEIGHT_WHAM", "_r_e_w_e_i_g_h_t__w_h_a_m.html", null ],
    [ "WHAM_HISTOGRAM", "_w_h_a_m__h_i_s_t_o_g_r_a_m.html", null ],
    [ "WHAM_WEIGHTS", "_w_h_a_m__w_e_i_g_h_t_s.html", null ],
    [ "AVERAGE", "_a_v_e_r_a_g_e.html", null ],
    [ "HISTOGRAM", "_h_i_s_t_o_g_r_a_m.html", null ],
    [ "MULTICOLVARDENS", "_m_u_l_t_i_c_o_l_v_a_r_d_e_n_s.html", null ],
    [ "CONVERT_TO_FES", "_c_o_n_v_e_r_t__t_o__f_e_s.html", null ],
    [ "DUMPCUBE", "_d_u_m_p_c_u_b_e.html", null ],
    [ "DUMPGRID", "_d_u_m_p_g_r_i_d.html", null ],
    [ "FIND_CONTOUR", "_f_i_n_d__c_o_n_t_o_u_r.html", null ],
    [ "FIND_CONTOUR_SURFACE", "_f_i_n_d__c_o_n_t_o_u_r__s_u_r_f_a_c_e.html", null ],
    [ "FIND_SPHERICAL_CONTOUR", "_f_i_n_d__s_p_h_e_r_i_c_a_l__c_o_n_t_o_u_r.html", null ],
    [ "FOURIER_TRANSFORM", "_f_o_u_r_i_e_r__t_r_a_n_s_f_o_r_m.html", null ],
    [ "GRID_TO_XYZ", "_g_r_i_d__t_o__x_y_z.html", null ],
    [ "INTEGRATE_GRID", "_i_n_t_e_g_r_a_t_e__g_r_i_d.html", null ],
    [ "INTERPOLATE_GRID", "_i_n_t_e_r_p_o_l_a_t_e__g_r_i_d.html", null ],
    [ "COLLECT_FRAMES", "_c_o_l_l_e_c_t__f_r_a_m_e_s.html", null ],
    [ "EUCLIDEAN_DISSIMILARITIES", "_e_u_c_l_i_d_e_a_n__d_i_s_s_i_m_i_l_a_r_i_t_i_e_s.html", null ],
    [ "PRINT_DISSIMILARITY_MATRIX", "_p_r_i_n_t__d_i_s_s_i_m_i_l_a_r_i_t_y__m_a_t_r_i_x.html", null ],
    [ "READ_DISSIMILARITY_MATRIX", "_r_e_a_d__d_i_s_s_i_m_i_l_a_r_i_t_y__m_a_t_r_i_x.html", null ],
    [ "LANDMARK_SELECT_FPS", "_l_a_n_d_m_a_r_k__s_e_l_e_c_t__f_p_s.html", null ],
    [ "LANDMARK_SELECT_RANDOM", "_l_a_n_d_m_a_r_k__s_e_l_e_c_t__r_a_n_d_o_m.html", null ],
    [ "LANDMARK_SELECT_STAGED", "_l_a_n_d_m_a_r_k__s_e_l_e_c_t__s_t_a_g_e_d.html", null ],
    [ "LANDMARK_SELECT_STRIDE", "_l_a_n_d_m_a_r_k__s_e_l_e_c_t__s_t_r_i_d_e.html", null ],
    [ "RESELECT_LANDMARKS", "_r_e_s_e_l_e_c_t__l_a_n_d_m_a_r_k_s.html", null ],
    [ "CLASSICAL_MDS", "_c_l_a_s_s_i_c_a_l__m_d_s.html", [
      [ "Method of optimization", "_c_l_a_s_s_i_c_a_l__m_d_s.html#dim-sec", null ]
    ] ],
    [ "OUTPUT_PCA_PROJECTION", "_o_u_t_p_u_t__p_c_a__p_r_o_j_e_c_t_i_o_n.html", null ],
    [ "PCA", "_p_c_a.html", null ],
    [ "PROJECT_ALL_ANALYSIS_DATA", "_p_r_o_j_e_c_t__a_l_l__a_n_a_l_y_s_i_s__d_a_t_a.html", null ],
    [ "SKETCHMAP_CONJGRAD", "_s_k_e_t_c_h_m_a_p__c_o_n_j_g_r_a_d.html", null ],
    [ "SKETCHMAP_POINTWISE", "_s_k_e_t_c_h_m_a_p__p_o_i_n_t_w_i_s_e.html", null ],
    [ "SKETCHMAP_READ", "_s_k_e_t_c_h_m_a_p__r_e_a_d.html", null ],
    [ "SKETCHMAP_SMACOF", "_s_k_e_t_c_h_m_a_p__s_m_a_c_o_f.html", null ],
    [ "SKETCH_MAP", "_s_k_e_t_c_h__m_a_p.html", null ],
    [ "SMACOF_MDS", "_s_m_a_c_o_f__m_d_s.html", null ],
    [ "OUTPUT_ANALYSIS_DATA_TO_COLVAR", "_o_u_t_p_u_t__a_n_a_l_y_s_i_s__d_a_t_a__t_o__c_o_l_v_a_r.html", null ],
    [ "OUTPUT_ANALYSIS_DATA_TO_PDB", "_o_u_t_p_u_t__a_n_a_l_y_s_i_s__d_a_t_a__t_o__p_d_b.html", null ]
];