var _analysis =
[
    [ "Reweighting and Averaging", "_analysis.html#analysisbias", null ],
    [ "Diagnostic tools", "_analysis.html#diag", null ],
    [ "Storing data for analysis", "_analysis.html#storing", null ],
    [ "Calculating dissimilarity matrices", "_analysis.html#dissimilaritym", null ],
    [ "Landmark Selection", "_analysis.html#landmarks", null ],
    [ "Dimensionality Reduction", "_analysis.html#dimred", null ],
    [ "Outputting the results from analysis algorithms", "_analysis.html#output", null ],
    [ "COMMITTOR", "_c_o_m_m_i_t_t_o_r.html", null ],
    [ "DUMPATOMS", "_d_u_m_p_a_t_o_m_s.html", null ],
    [ "DUMPDERIVATIVES", "_d_u_m_p_d_e_r_i_v_a_t_i_v_e_s.html", null ],
    [ "DUMPFORCES", "_d_u_m_p_f_o_r_c_e_s.html", null ],
    [ "DUMPMASSCHARGE", "_d_u_m_p_m_a_s_s_c_h_a_r_g_e.html", null ],
    [ "DUMPPDB", "_d_u_m_p_p_d_b.html", null ],
    [ "DUMPPROJECTIONS", "_d_u_m_p_p_r_o_j_e_c_t_i_o_n_s.html", null ],
    [ "DUMPVECTOR", "_d_u_m_p_v_e_c_t_o_r.html", null ],
    [ "PRINT", "_p_r_i_n_t.html", "_p_r_i_n_t" ],
    [ "PRINT_NDX", "_p_r_i_n_t__n_d_x.html", null ],
    [ "SELECT_COMPONENTS", "_s_e_l_e_c_t__c_o_m_p_o_n_e_n_t_s.html", null ],
    [ "SELECT_WITH_MASK", "_s_e_l_e_c_t__w_i_t_h__m_a_s_k.html", null ],
    [ "UPDATE_IF", "_u_p_d_a_t_e__i_f.html", null ],
    [ "COVARIANCE_MATRIX", "_c_o_v_a_r_i_a_n_c_e__m_a_t_r_i_x.html", null ],
    [ "REWEIGHT_BIAS", "_r_e_w_e_i_g_h_t__b_i_a_s.html", null ],
    [ "REWEIGHT_METAD", "_r_e_w_e_i_g_h_t__m_e_t_a_d.html", null ],
    [ "REWEIGHT_TEMP_PRESS", "_r_e_w_e_i_g_h_t__t_e_m_p__p_r_e_s_s.html", null ],
    [ "WHAM", "_w_h_a_m.html", null ],
    [ "WHAM_HISTOGRAM", "_w_h_a_m__h_i_s_t_o_g_r_a_m.html", null ],
    [ "WHAM_WEIGHTS", "_w_h_a_m__w_e_i_g_h_t_s.html", null ],
    [ "ACCUMULATE", "_a_c_c_u_m_u_l_a_t_e.html", null ],
    [ "AVERAGE", "_a_v_e_r_a_g_e.html", null ],
    [ "CUSTOM_GRID", "_c_u_s_t_o_m__g_r_i_d.html", null ],
    [ "EVALUATE_FUNCTION_FROM_GRID", "_e_v_a_l_u_a_t_e__f_u_n_c_t_i_o_n__f_r_o_m__g_r_i_d.html", null ],
    [ "EVALUATE_FUNCTION_FROM_GRID_SCALAR", "_e_v_a_l_u_a_t_e__f_u_n_c_t_i_o_n__f_r_o_m__g_r_i_d__s_c_a_l_a_r.html", null ],
    [ "EVALUATE_FUNCTION_FROM_GRID_VECTOR", "_e_v_a_l_u_a_t_e__f_u_n_c_t_i_o_n__f_r_o_m__g_r_i_d__v_e_c_t_o_r.html", null ],
    [ "FIND_GRID_MAXIMUM", "_f_i_n_d__g_r_i_d__m_a_x_i_m_u_m.html", null ],
    [ "FIND_GRID_MINIMUM", "_f_i_n_d__g_r_i_d__m_i_n_i_m_u_m.html", null ],
    [ "HISTOGRAM", "_h_i_s_t_o_g_r_a_m.html", null ],
    [ "INTEGRATE_GRID", "_i_n_t_e_g_r_a_t_e__g_r_i_d.html", null ],
    [ "MATHEVAL_GRID", "_m_a_t_h_e_v_a_l__g_r_i_d.html", null ],
    [ "MULTICOLVARDENS", "_m_u_l_t_i_c_o_l_v_a_r_d_e_n_s.html", null ],
    [ "REFERENCE_GRID", "_r_e_f_e_r_e_n_c_e__g_r_i_d.html", null ],
    [ "SUM_GRID", "_s_u_m__g_r_i_d.html", null ],
    [ "CONVERT_TO_FES", "_c_o_n_v_e_r_t__t_o__f_e_s.html", null ],
    [ "DUMPCONTOUR", "_d_u_m_p_c_o_n_t_o_u_r.html", null ],
    [ "DUMPCUBE", "_d_u_m_p_c_u_b_e.html", null ],
    [ "DUMPGRID", "_d_u_m_p_g_r_i_d.html", null ],
    [ "FIND_CONTOUR", "_f_i_n_d__c_o_n_t_o_u_r.html", null ],
    [ "FIND_CONTOUR_SURFACE", "_f_i_n_d__c_o_n_t_o_u_r__s_u_r_f_a_c_e.html", null ],
    [ "FIND_SPHERICAL_CONTOUR", "_f_i_n_d__s_p_h_e_r_i_c_a_l__c_o_n_t_o_u_r.html", null ],
    [ "FOURIER_TRANSFORM", "_f_o_u_r_i_e_r__t_r_a_n_s_f_o_r_m.html", null ],
    [ "INTERPOLATE_GRID", "_i_n_t_e_r_p_o_l_a_t_e__g_r_i_d.html", null ],
    [ "COLLECT_FRAMES", "_c_o_l_l_e_c_t__f_r_a_m_e_s.html", null ],
    [ "FARTHEST_POINT_SAMPLING", "_f_a_r_t_h_e_s_t__p_o_i_n_t__s_a_m_p_l_i_n_g.html", null ],
    [ "LANDMARK_SELECT_FPS", "_l_a_n_d_m_a_r_k__s_e_l_e_c_t__f_p_s.html", null ],
    [ "LANDMARK_SELECT_RANDOM", "_l_a_n_d_m_a_r_k__s_e_l_e_c_t__r_a_n_d_o_m.html", null ],
    [ "LANDMARK_SELECT_STRIDE", "_l_a_n_d_m_a_r_k__s_e_l_e_c_t__s_t_r_i_d_e.html", null ],
    [ "ARRANGE_POINTS", "_a_r_r_a_n_g_e__p_o_i_n_t_s.html", null ],
    [ "CLASSICAL_MDS", "_c_l_a_s_s_i_c_a_l__m_d_s.html", [
      [ "Method of optimization", "_c_l_a_s_s_i_c_a_l__m_d_s.html#dim-sec", null ]
    ] ],
    [ "CREATE_MASK", "_c_r_e_a_t_e__m_a_s_k.html", null ],
    [ "PCA", "_p_c_a.html", null ],
    [ "PROJECT_POINTS", "_p_r_o_j_e_c_t__p_o_i_n_t_s.html", null ],
    [ "SKETCHMAP", "_s_k_e_t_c_h_m_a_p.html", null ],
    [ "SKETCHMAP_PROJECTION", "_s_k_e_t_c_h_m_a_p__p_r_o_j_e_c_t_i_o_n.html", null ]
];