var _colvar =
[
    [ "ADAPTIVE_PATH", "_a_d_a_p_t_i_v_e__p_a_t_h.html", null ],
    [ "ALPHABETA", "_a_l_p_h_a_b_e_t_a.html", null ],
    [ "ALPHARMSD", "_a_l_p_h_a_r_m_s_d.html", null ],
    [ "ANGLE", "_a_n_g_l_e.html", null ],
    [ "ANTIBETARMSD", "_a_n_t_i_b_e_t_a_r_m_s_d.html", null ],
    [ "CELL", "_c_e_l_l.html", null ],
    [ "CONSTANT", "_c_o_n_s_t_a_n_t.html", null ],
    [ "CONTACTMAP", "_c_o_n_t_a_c_t_m_a_p.html", null ],
    [ "COORDINATION", "_c_o_o_r_d_i_n_a_t_i_o_n.html", null ],
    [ "DHENERGY", "_d_h_e_n_e_r_g_y.html", null ],
    [ "DIHCOR", "_d_i_h_c_o_r.html", null ],
    [ "DIMER", "_d_i_m_e_r.html", null ],
    [ "DIPOLE", "_d_i_p_o_l_e.html", null ],
    [ "DISTANCE", "_d_i_s_t_a_n_c_e.html", null ],
    [ "DISTANCE_FROM_CONTOUR", "_d_i_s_t_a_n_c_e__f_r_o_m__c_o_n_t_o_u_r.html", null ],
    [ "EEFSOLV", "_e_e_f_s_o_l_v.html", null ],
    [ "ENERGY", "_e_n_e_r_g_y.html", null ],
    [ "ERMSD", "_e_r_m_s_d.html", null ],
    [ "EXTRACV", "_e_x_t_r_a_c_v.html", null ],
    [ "FAKE", "_f_a_k_e.html", null ],
    [ "GHBFIX", "_g_h_b_f_i_x.html", null ],
    [ "GPROPERTYMAP", "_g_p_r_o_p_e_r_t_y_m_a_p.html", null ],
    [ "GYRATION", "_g_y_r_a_t_i_o_n.html", null ],
    [ "PARABETARMSD", "_p_a_r_a_b_e_t_a_r_m_s_d.html", null ],
    [ "PATH", "_p_a_t_h.html", null ],
    [ "PATHMSD", "_p_a_t_h_m_s_d.html", null ],
    [ "PCAVARS", "_p_c_a_v_a_r_s.html", null ],
    [ "POSITION", "_p_o_s_i_t_i_o_n.html", null ],
    [ "PROJECTION_ON_AXIS", "_p_r_o_j_e_c_t_i_o_n__o_n__a_x_i_s.html", null ],
    [ "PROPERTYMAP", "_p_r_o_p_e_r_t_y_m_a_p.html", null ],
    [ "PUCKERING", "_p_u_c_k_e_r_i_n_g.html", null ],
    [ "TEMPLATE", "_t_e_m_p_l_a_t_e.html", null ],
    [ "TORSION", "_t_o_r_s_i_o_n.html", null ],
    [ "VOLUME", "_v_o_l_u_m_e.html", null ]
];